-- Feel free to modify this file to match your development goal.
-- Here we only create 3 tables for demo purpose.

CREATE TABLE Users (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    firstname VARCHAR(255) NOT NULL,
    lastname VARCHAR(255) NOT NULL
);

CREATE TABLE Products (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) UNIQUE NOT NULL,
    price DECIMAL(12,2) NOT NULL,
    available BOOLEAN DEFAULT TRUE
);

CREATE TABLE Purchases(
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    uid INT NOT NULL REFERENCES Users(id),
    pid INT NOT NULL REFERENCES Products(id),
    time_purchased timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC')
);

CREATE TABLE Committees (
    cid INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    from_entity VARCHAR(255) NOT NULL,
    to_entity VARCHAR(255) NOT NULL,
    donation_amount DECIMAL(20,2) NOT NULL,
    from_category VARCHAR(255), --!CHECK (from_category="PAC" ),--
    to_category VARCHAR (255), --!CHECK (to_category="candidate"),--
    yr INT NOT NULL
);

CREATE TABLE Issues (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    policy_category VARCHAR(255) NOT NULL,
    politician VARCHAR(255) NOT NULL,
    donor VARCHAR(255), --!CHECK (from_category="PAC" ),--
    donor_industry VARCHAR (255), --!CHECK (to_category="candidate"),--
    donation_amount DECIMAL(20,2) NOT NULL,
    yr INT NOT NULL,
    legislation VARCHAR(255),
    vote VARCHAR(255),
    link VARCHAR(255)
);
    
CREATE TABLE States (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    state_id VARCHAR(255) NOT NULL,
    year INTEGER NOT NULL,
    candidate_name VARCHAR(255) NOT NULL,
    party VARCHAR(255) NOT NULL,
    incumbent_status VARCHAR(255) NOT NULL,
    total_receipts DECIMAL(20,2) NOT NULL,
    percent_vote DECIMAL (20,2) NOT NULL
); 

CREATE TABLE Correlation (
    state_id VARCHAR(255) NOT NULL,
    donator_id VARCHAR(255) NOT NULL,
    issue VARCHAR(255) NOT NULL,
    candidate_id VARCHAR(255) NOT NULL,
    committee_id INTEGER NOT NULL,
    amount DECIMAL(20,2) NOT NULL,
    passed VARCHAR(255) NOT NULL
);

CREATE TABLE Candidate_Member_Votes (
    congress INT NOT NULL,
    chamber VARCHAR(255) NOT NULL,
    rollnumber INT NOT NULL,
    icpsr DECIMAL (20,2) NOT NULL,
    cast_code DECIMAL (20,2) NOT NULL,
    prob VARCHAR(255),
    PRIMARY KEY(congress, rollnumber, icpsr)
);

CREATE TABLE Vote_Cast_Code (
    cast_code DECIMAL (20,2) NOT NULL,
    descr VARCHAR(255) NOT NULL,
    PRIMARY KEY(cast_code)
);

CREATE TABLE Candidate_Vote_Data (
    congress INT NOT NULL,
    chamber VARCHAR(255) NOT NULL,
    rollnumber INT NOT NULL,
    vote_date DATE NOT NULL,
    vote_session DECIMAL (20,2),
    clerk_rollnumber DECIMAL (20,2),
    yea_count INT,
    nay_count INT,
    nominate_mid_1 DECIMAL (20,2),
    nominate_mid_2 DECIMAL (20,2),
    nominate_spread_1 DECIMAL (20,2),
    nominate_spread_2 DECIMAL (20,2),
    nominate_log_likelihood DECIMAL (20,2),
    bill_number VARCHAR(225),
    vote_result VARCHAR(225),
    vote_desc VARCHAR(3750),
    vote_question VARCHAR(225),
    dtl_desc VARCHAR(2800),
    PRIMARY KEY(rollnumber, congress)
);

CREATE TABLE Candidate_Members (
    congress INT NOT NULL,
    chamber VARCHAR(255) NOT NULL,
    icpsr DECIMAL (20,2) NOT NULL,
    state_icpsr INT NOT NULL,
    district_code DECIMAL (20,2) NOT NULL,
    state_abbrev VARCHAR(255) NOT NULL,
    party_code INT NOT NULL,
    occupancy INT,
    last_means INT,
    bioname VARCHAR(255) NOT NULL,
    bioguide_id VARCHAR(255),
    born DECIMAL (20,2),
    died DECIMAL (20,2),
    nominate_dim1 DECIMAL (20,2),
    nominate_dim2 DECIMAL (20,2),
    nominate_log_likelihood DECIMAL (20,2),
    nominate_geo_mean_probability DECIMAL (20,2),
    nominate_number_of_votes DECIMAL (20,2),
    nominate_number_of_errors DECIMAL (20,2),
    conditional DECIMAL (20,2),
    nokken_poole_dim1 DECIMAL (20,2),
    nokken_poole_dim2 DECIMAL (20,2),
    PRIMARY KEY(congress, icpsr)
);

CREATE TABLE Candidate_Party_Codes (
    party_code INT NOT NULL,
    party VARCHAR(255) NOT NULL,
    PRIMARY KEY(party_code)
);

--implement search bar by category
--search by from and to whichever entity
